name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: ["black", "bandit", "pylint", "flake8"]
        include:
          - tools: pytest
            args: ""

    steps:
      - uses: actions/checkout@v4

      # (Opcional) Azure login, si es que lo requieres
      - uses: Azure/login@v1.5.1
        continue-on-error: true
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 1. Configura Python (la versi칩n que usar치s)
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      # 2. Instala las dependencias (por ejemplo, tu proyecto + extras)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      # 3. Corre la acci칩n de Microsoft, que ya asume que est치 todo instalado
      - name: ${{ matrix.tools }}
        uses: microsoft/action-python@0.7.2
        with:
          ${{ matrix.tools }}: true
          args: ${{ matrix.args }}
          # Si el template expone workdir/testdir/python_version como inputs:
          workdir: "."
          testdir: "tests"
          python_version: "3.11.3"
